import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-screen">
          {/* Common Page Header */}
          <header className="bg-white shadow p-4 flex justify-between items-center">
            <nav className="flex space-x-4">
              <Link href="/dashboard" className="hover:underline">
                Dashboard
              </Link>
              <Link href="/cases" className="hover:underline">
                Cases
              </Link>
              <Link href="/case-history" className="hover:underline">
                Case History
              </Link>
            </nav>
          </header>

          {/* Main Content Area */}
          <div className="flex-1 flex flex-col">
            {/* Main Content */}
            <main className="p-4 flex-1 overflow-y-auto">{children}</main>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
