import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen">
          {/* Sidebar */}
          <aside className="w-64 bg-gray-800 text-white flex flex-col">
            <div className="p-4 text-lg font-bold">Case Dashboard</div>
            <nav className="flex-1">
              <ul className="space-y-2 p-4">
                <li>
                  <Link href="/dashboard" className="block p-2 hover:bg-gray-700">
                    Dashboard
                  </Link>
                </li>
                <li>
                  <Link href="/cases" className="block p-2 hover:bg-gray-700">
                    Cases
                  </Link>
                </li>
                <li>
                  <Link href="/case-history" className="block p-2 hover:bg-gray-700">
                    Case History
                  </Link>
                </li>
              </ul>
            </nav>
          </aside>

          {/* Main Content Area */}
          <div className="flex-1 flex flex-col">
            {/* Top Navigation Bar */}
            <header className="bg-white shadow p-4 flex justify-between items-center">
            </header>

            {/* Main Content */}
            <main className="p-4 flex-1 overflow-y-auto">{children}</main>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
